services:
  cache_redis:
    image: redis:8.10.2-alpine
    working_dir: /data
    user: "987:987"
    volumes:
      - ./redis_conf:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server /data/redis.conf
    networks:
      common: